fun/urls.py
from django.urls import path	
from . import views


app_name = 'fun'

urlpatterns = [
    path('', views.fun_home, name='fun_home'),
] 

home/urls.py
from django.urls import path
from home.views import Home, About, Feedback

app_name = 'Home'

urlpatterns=[
    path('',Home,name='Home'),
    path('about',Feedback,name='About'),
]

info_PJJ/urls.py
from django.urls import path
from info_PJJ.views import Add_News_PJJ,Learn_From_Home

app_name = 'info_PJJ'

urlpatterns=[
    path('Add_Information_Learn_From_Home',Add_News_PJJ,name='Add_News_PJJ'),
    path('Learn_From_Home',Learn_From_Home,name='Learn_From_Home'),
]

info_covid/urls.py
from django.urls import path	

from . import views

app_name = 'info_covid'

urlpatterns = [
    path('', views.covid_per_country, name='covid_case_per_country'),
    path('country/', views.country_detail, name='country_detail'),
]

informasi_wfh/urls.py
from django.urls import path	

from . import views

app_name = 'informasi_wfh'

urlpatterns = [
    path('', views.list_informasi_wfh, name='list_informasi_wfh'),
    path('add', views.add_informasi_wfh, name='add_informasi_wfh'),
]

plandemic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('Hello', include('hello.urls')),
    path('Information/',include('info_PJJ.urls')),
    path('wfh/', include('informasi_wfh.urls')),
    path('planner/', include('planner.urls')),
    path('accounts/', include('accounts.urls')),
    path('covid/', include('info_covid.urls')),
    path('fun/', include('fun.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

planner/urls.py
from django.urls import path
from .views import Listplan, fungsi_data
from . import views

app_name = 'planner'

urlpatterns = [
    path('', Listplan.as_view(),name="planner"),
    path('data/',views.fungsi_data,name='data'),
]

home/models.py
# from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
# Create by Zaidan

class Feedback(models.Model):
    id = models.AutoField(primary_key=True,)
    isi_feedback = models.TextField()
    nama_pengisi_feedback = models.CharField(max_length = 50)

    
class FeedbackBaru(models.Model):
    # post = models.ForeignKey(Post)
    name = models.CharField(max_length=100, null=True)
    content = models.CharField(max_length=160)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Feedback-{}'.format(name)
    

home/forms.py
from django import forms
from .models import Feedback, FeedbackBaru

class FeedbackForms(forms.ModelForm):
    class Meta : 
        model = Feedback
        fields = ["isi_feedback","nama_pengisi_feedback"]
        widgets = {
            'isi_feedback':forms.Textarea(attrs={'class':'form-control'}),
            'nama_pengisi_feedback':forms.TextInput(attrs={'class':'form-control'})}


class FeedbackFormBaru(forms.ModelForm):
    class Meta:
        model = FeedbackBaru
        fields = '__all__'
        widgets = {
            'name':forms.TextInput(
                attrs={
                    'class':'form-control',
                }
            ),
            'content':forms.Textarea(
                attrs={
                    'class':'form-control',
                },
            )
        }
        labels = {
            "content": "Feedback"
        }


            

home/views.py
from django.shortcuts import render,redirect
from .forms import FeedbackForms, FeedbackFormBaru
from .models import FeedbackBaru
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string



# Create your views here.
def Home(request):
    return render(request,'Home/Home.html')

def About(request):
    if request.method ==  "POST":
        form1 = FeedbackForms(request.POST)
        if form1.is_valid():
            form1.save()
            return redirect('Home:About')
    else :      
        form = FeedbackForms()
        return render(request, 'Home/about.html',{"form_html" : form})

def Feedback(request):
    feedbacks = FeedbackBaru.objects.all()

    if request.method == "POST":
        form_feedback = FeedbackFormBaru(request.POST or None)
        if form_feedback.is_valid():
            name = request.POST.get('name')
            content = request.POST.get('content')
            feedback = FeedbackBaru.objects.create(name=name, content=content)
            feedback.save()
            # return HttpResponseRedirect('/about')
    else:
        form_feedback = FeedbackFormBaru()

    context = {
        'feedbacks':feedbacks,
        'form_feedback':form_feedback,
    }

    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form':html})

    return render(request, 'Home/about.html', context)

home/templates/Home/Home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Home</title>

    <!--Montserrat Font-->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'home/styleHome.css' %}">
</head>


<body>
    <h1 id="heading">PLANDEMIC</h1>

    <div class="container" onclick="expand()">
        <div class="toggle" id="toggle">
            <img src="{% static 'img/Group 11.svg' %}" class="img4">
        </div>
    </div>

    <div class="menu" id="menu">
        <div class="item">
            <a href="{% url 'fun:fun_home' %}">
                <img src="{% static 'img/Group 31.svg' %}"  class="img1">
            </a>
        </div>

        <div class="item">
            <a href="{% url 'Home:About' %}">
                <img src="{% static 'img/Group 8.svg' %}" class="img2">
            </a>
        </div>

        <div class="item">
            <a href="{% url 'info_covid:covid_case_per_country' %}">
                <img src="{% static 'img/Group 15.svg' %}" class="img3">
            </a>
        </div>

        <div class="item">
            <a href="{% url 'info_PJJ:Learn_From_Home' %}">
                <img src="{% static 'img/Group 25.svg' %}" class="img3">
            </a>
        </div>

        <div class="item">
            <a href="{% url 'informasi_wfh:list_informasi_wfh' %}">
                <img src="{% static 'img/Group 27.svg' %}" class="img3">
            </a>
        </div>

        <div class="item">
            <a href="{% url 'planner:planner' %}">
                <img src="{% static 'img/Group 26.svg' %}" class="img6">
            </a>
        </div>
    </div>

<script type="text/javascript"> /*cari google*/
var j=0;
var i=document.getElementById("menu").childNodes;
function expand(){
    if(j==0){

        i[1].style.transform='translateY(-160px)';
        i[3].style.transform='translate(140px,-80px)';
        i[5].style.transform='translate(140px,80px)';
        i[7].style.transform='translateY(160px)';
        i[9].style.transform='translate(-140px,80px)';
        i[11].style.transform='translate(-140px,-80px)';
        j=1;
        document.getElementById("heading").style.opacity=0;
        document.getElementById("heading").style.transition= "1s";

    }
    else{

        i[1].style.transform='translateY(0)';
        i[3].style.transform='translate(0)';
        i[5].style.transform='translate(0)';
        i[7].style.transform='translateY(0)';
        i[9].style.transform='translate(0)';
        i[11].style.transform='translate(0)';
        j=0;
        document.getElementById("heading").style.opacity=1;
        document.getElementById("heading").style.transition= "1s";
    }
}
</script>

</body>
</html>

home/templates/Home/about.html
{% extends 'Home/base.html' %}
{% load static %}

{% block title %}
<title>About Us</title>
{% endblock %}

{% block style-css %}
<link rel="stylesheet" href="{% static 'home/styleHome.css' %}">
{% endblock %}

{% block sections %}
<section class="about d-flex flex-column justify-content-center">
	<div class="container-about rounded text-center mx-auto p-4">
		<div class="about-text mx-auto mb-5">
			<h3 class="mb-4"> About Us </h3>
			<p> Hello! We are from Faculty of Computer Science, University of Indonesia. <br /> This web is created to help anyone manage their schedule and get an up-to-date news in this pandemic situation. </p>
		</div>
		<div class="linked-in-container">
			<div class="author">
				<span class="social"><img src="{% static 'img/logo-linkedin-custom-plandemic.svg' %}"><a href="https://www.linkedin.com/in/aisha-salsabila-0904/"> Aisha Salsabila</a> </span>
				<span class="social"><img src="{% static 'img/logo-linkedin-custom-plandemic.svg' %}"><a href="https://www.linkedin.com/in/alisha-yumna-bakri-922682166/"> Alisha Yumna Bakri</a> </span>
				<span class="social"><img src="{% static 'img/logo-linkedin-custom-plandemic.svg' %}"><a href="https://id.linkedin.com/in/kaysa-swa-20814b1a4"> Kaysa Syifa </a> </span>
				<span class="social"><img src="{% static 'img/logo-linkedin-custom-plandemic.svg' %}"><a href="https://www.linkedin.com/in/zaidan-ariiq-29048a193/"> M. Zaidan Ariiq </a> </span>
				<span class="social"><img src="{% static 'img/logo-linkedin-custom-plandemic.svg' %}"><a href="https://www.linkedin.com/in/nabiladita/"> Nabila Dita </a> </span>
			</div>
		</div>

		<br><br>
		<div class="main-feedback-section">
			{% include 'Home/feedback.html' %}
		</div>
		
	</div>
</section>

<script>
	$(document).on('submit', '.comment-form', function(event){
		event.preventDefault();
		$.ajax({
			type: 'POST',
			url: $(this.attr('action')),
			data: $(this).serialize(),
			dataType: 'json',
			success: function(response) {
				$('.main-feedback-section').html(response['form']);
				$('inputarea').val('');
			},
			error: function(rs, e) {
				console.log(rs.responseText);
			},
		})
	})
</script>

{% endblock %}

home/templates/Home/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
	<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block title %}

	{% endblock title %}

    <!--Montserrat Font-->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

	<!--Bootstrap-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" 
	crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->

	<link rel="stylesheet" href="{% static 'home/navbar.css' %}">
	{% block style-css %}

	{% endblock %}
	</head>

	<body>
	<!-- navbar -->
	<nav class="navbar navbar-expand-lg fixed-top">
		<button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mx-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'Home:Home' %}">HOME</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'fun:fun_home' %}">FUN</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'planner:planner' %}">PLANNER</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> INFORMATION </a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{% url 'info_covid:covid_case_per_country' %}">COVID-19</a>
						<a class="dropdown-item" href="{% url 'informasi_wfh:list_informasi_wfh' %}" >Work From Home</a>
						<a class="dropdown-item" href="{% url 'info_PJJ:Learn_From_Home' %}">Learn From Home</a>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'Home:About' %}">ABOUT</a>
				</li>
				
				<li class="nav-item">
					{% if user.is_authenticated == False %} 					
						<a class="nav-link active" type="submit" href="/accounts/login">LOGIN</a>
					{% else %}									
						<a class="nav-link active" type="submit" href="/accounts/logout">LOG OUT</a>
					{% endif %}
				</li>
				
			</ul>
		</div>
	</nav>
	{% block sections %}

	{% endblock sections %}
	</body>
</html>

home/templates/Home/feedback.html
{% load static %}

<div class="feedback-text mx-auto mb-1">
	<br>
	<h3 class="mb-4"> Feedback </h3>
	<p> Tell us about your experience on this web to make it better!</p>

	{% if user.is_authenticated %}
		<form method="POST" class="feedback-form" action="/about">
			{% csrf_token %}
			{{ form_feedback.as_p }}
			
			<input type="submit" value="Submit" class="btn btn-outline-success">
		</form>

		<br><br>

		<div class="justify-content-center">
			<h3><hr> {{ feedbacks.count }} Feedback{{ feedbacks|pluralize }} <hr></h3>
			<br>
			{% for feedback in feedbacks %}
				<blockquote class="blockquote">
					<p class="mb-0" style="font-size=1em">{{ feedback.content }}</p>
					<figcaption class="blockquote-footer">
						by <cite title="Source Title">{{ feedback.name|capfirst }}</cite>
					</figcaption>
				</blockquote>
				<br>
			{% endfor %}
		</div>
	{% else %}
		<p>Please <a class="social" href="/accounts/login">login</a> to give and view feedback(s)</p>
	{% endif %}
</div>