fun/urls.py
from django.urls import path	
from . import views


app_name = 'fun'

urlpatterns = [
    path('', views.fun_home, name='fun_home'),
] 

informasi_wfh/urls.py
from django.urls import path	

from . import views

app_name = 'informasi_wfh'

urlpatterns = [
    path('', views.list_informasi_wfh, name='list_informasi_wfh'),
    path('add', views.add_informasi_wfh, name='add_informasi_wfh'),
]

plandemic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('Hello', include('hello.urls')),
    path('Information/',include('info_PJJ.urls')),
    path('wfh/', include('informasi_wfh.urls')),
    path('planner/', include('planner.urls')),
    path('accounts/', include('accounts.urls')),
    path('covid/', include('info_covid.urls')),
    path('fun/', include('fun.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informasi_wfh/models.py
from django.db import models
from django.forms.widgets import TextInput

# Create your models here.
class InformasiWFH(models.Model):
    title = models.CharField(max_length=100, null=True)
    link = models.URLField(max_length=500, null=True)
    short_Description = models.CharField(max_length=1000, null=True)

informasi_wfh/forms.py
from django import forms
from .models import InformasiWFH

class Input_News(forms.ModelForm):
    class Meta:
        model = InformasiWFH
        fields = [
            'title',
            'link',
            'short_Description',
        ]
        widgets = {
            'title' : forms.TextInput(
                attrs={
                'class':'form-style',
                }),
            'link': forms.TextInput(attrs={
                'class':'form-style',
                'placeholder': 'Please start with http://'
                }),
            'short_Description': forms.Textarea(
                attrs={
                    'rows': 7,
                    'class':'form-style',
                    }),
        }

informasi_wfh/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import InformasiWFH
from informasi_wfh.forms import Input_News

from django.contrib.auth.decorators import login_required

from django.http import JsonResponse
from django.forms.models import model_to_dict

# Create your views here.
def list_informasi_wfh(request):
	form = Input_News(request.POST or None)
	list_informasi = InformasiWFH.objects.all()

	if form.is_valid():
		informasi = form.save()
		return JsonResponse({'informasi':model_to_dict(informasi)}, status=200)
	
	response = {'form' : form ,
				'list_informasi': list_informasi}

	return render(request, 'wfh/list.html', response)

@login_required(login_url='/accounts/login')
def add_informasi_wfh(request):
	form = Input_News(request.POST or None)
	if form.is_valid():
			form.save()
			return redirect("/wfh")
	else:
		response = { 'form' : form }
		return render(request, 'wfh/add-wfh.html', response)

informasi_wfh/templates/wfh/add-wfh.html
{% extends 'wfh/base-wfh.html' %}

{% block title %}
<title>Add More Information</title>
{% endblock %}

{% block sub-section %}
<section class="add-section">
	<div class="box rounded">
		<h4> Add News </h4>
		<form action="{% url 'informasi_wfh:add_informasi_wfh' %}" method="POST">
        	{% csrf_token %}
        	{{ form.as_p }}
        	<input type="submit" value="ADD" class="submit"/>
    	</form>

	</div>
</section>
{% endblock %}

informasi_wfh/templates/wfh/base-wfh.html
{% extends 'Home/base.html' %}
{% load static %}
	{% block title %}
		{% block heading %}

        {% endblock heading %}
	{% endblock title %}

	{% block style-css %}
		<link rel="stylesheet" href="{% static 'wfh/wfh.css'  %}">
	{% endblock style-css %}
	
	{% block sections %}
		{% block sub-section %}
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

		
		{% endblock sub-section %}
	{% endblock sections %}
	

informasi_wfh/templates/wfh/list.html
{% extends 'wfh/base-wfh.html' %}

{% block heading %}
<title>Work From Home</title>
{% endblock %}

{% block sub-section %}
<section>
	<h3>Information About Work From Home</h3>
	<button class="rounded add_informasi px-3 py-2" data-modal-target='#wfhNews' id="addNews"> <a>Add more information</a> </button>

	<div class="wfh-news" id="wfhNews">
		<div class="box rounded" id="box">
			<h4> Add News </h4>
			<form method="POST" id="post-form" data-url="{% url 'informasi_wfh:list_informasi_wfh' %}">
	        	{% csrf_token %}
	        	{{ form.as_p }}
	        	<input type="submit" value="ADD" class="submit"/>
	    	</form>
		</div>
		
		<article class="text-left">
			{% for informasi in list_informasi %}
			<div class="card card-left">
				<div class="card-body">
					<h5 class="card-title">{{informasi.title}}</h5>
					<p class="card-text">{{informasi.short_Description}}</p>
					<a class="btn btn-primary" href={{informasi.link}} id="read-more"> Read more</a>
				</div>
			</div>
			{% endfor %}	
		</article>
	</div>
	<div id="overlay"></div>
</section>


<script  type="text/javascript">
$(document).ready(function($){
	const addNews = document.querySelectorAll('[data-modal-target]');
	const overlay = document.getElementById('overlay');

	$('#addNews').click(function() {
		const box = document.getElementById('box');
		box.classList.add('active');
		overlay.classList.add('active');
	});

	$(overlay).click(function(){
		const box = document.getElementById('box');
		box.classList.remove('active');
		overlay.classList.remove('active');
	});

    $("#post-form").submit(function(e){
        e.preventDefault();

       var serializedData = $('#post-form').serialize();

       $.ajax({
       		url: $('#post-form').data('url'),
       		data: serializedData,
       		type: 'post',
       		success: function(response){
       			$('article').append('<div class="card card-left"> <div class="card-body"> <h5 class="card-title">' + response.informasi.title + '</h5> <p class="card-text">' + response.informasi.short_Description + '</p> <a class="btn btn-primary" href="' + response.informasi.link +  '">Read more</a> </div> </div>');
       		const box = document.getElementById('box');
			box.classList.remove('active');
			overlay.classList.remove('active');
       		},
       });
       $("#post-form").trigger("reset");
    });
    
    $('.card-body').mouseover(function(){
    	var index = $('.card-body').index(this);
    	$('.card-body:eq('+index+')').css('background-color', '#e7e7e7');
    });

    $('.card-body').mouseleave(function(){
    	var index = $('.card-body').index(this);
    	$('.card-body:eq('+index+')').css('background-color', 'white');
    });
});
</script>
{% endblock %}