fun/urls.py
from django.urls import path	
from . import views


app_name = 'fun'

urlpatterns = [
    path('', views.fun_home, name='fun_home'),
] 

info_PJJ/urls.py
from django.urls import path
from info_PJJ.views import Add_News_PJJ,Learn_From_Home

app_name = 'info_PJJ'

urlpatterns=[
    path('Add_Information_Learn_From_Home',Add_News_PJJ,name='Add_News_PJJ'),
    path('Learn_From_Home',Learn_From_Home,name='Learn_From_Home'),
]

plandemic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('Hello', include('hello.urls')),
    path('Information/',include('info_PJJ.urls')),
    path('wfh/', include('informasi_wfh.urls')),
    path('planner/', include('planner.urls')),
    path('accounts/', include('accounts.urls')),
    path('covid/', include('info_covid.urls')),
    path('fun/', include('fun.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info_PJJ/models.py
from django.db import models

# Create your models here.
class Form_Add_News_PJJ(models.Model):
    Title = models.CharField(max_length=200)
    Link = models.URLField(max_length = 200)
    Short_Description = models.TextField()

info_PJJ/forms.py
from django import forms
from .models import Form_Add_News_PJJ

class Add_News_PJJ_Form(forms.ModelForm):
    class Meta:
        model = Form_Add_News_PJJ
        fields = [
            'Title',
            'Link',
            'Short_Description'
        ]

       

info_PJJ/views.py
from django.shortcuts import render,redirect
from .forms import Add_News_PJJ_Form
from .models import Form_Add_News_PJJ
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/accounts/login')
def Add_News_PJJ(request):
    form = Add_News_PJJ_Form()
    model = Form_Add_News_PJJ

    if request.method=="POST":
        form=Add_News_PJJ_Form(request.POST)
        if form.is_valid():
            Title=request.POST.get("Title")
            Link=request.POST.get("Link")
            Short_Description=request.POST.get("Short_Description")
            form.save()

        context={
            'form':form
        }

        return redirect('info_PJJ:Learn_From_Home')

    else:
        context = {
            'form' : form
        }

    return render(request,'info_PJJ/Add_News_PJJ.html',context)

def Learn_From_Home(request):
    model = Form_Add_News_PJJ

    News = Form_Add_News_PJJ.objects.all()
 
    response={
        'News' : News
    }

    return render(request,'info_PJJ/Learn_From_Home.html',response)

info_PJJ/templates/info_PJJ/Add_News_PJJ.html
{% extends 'info_PJJ/base.html' %}

{% load static %}

<html>


    {% block heading %}
   
        <title>Add News Learn From Home</title>
    
    {% endblock heading %}

    {% block content %}
    
    <section class="body1">
        <div class="form">
            <div class="heading">
                <h1 style="text-align: center;font-family: Montserrat;margin-top: 1em;font-size: 30px;">Add News</h1>
            </div>

            <div class="add-news">

                <form method="POST">
                    {% csrf_token %}
                    
                    <div class="form-title" style="width: 100px;height: 30px;margin:45px;right:1rem;position: relative;">
                        <label style="margin-bottom: 0;">Title</label>
                        {{form.Title}}
                    </div>

                    <div class="form-Link" style="width: 100px;height: 30px;margin:45px;right:1rem;position: relative;">
                        <label style="margin-bottom: 0;">Link</label>
                        {{form.Link}}
                    </div>

                    <div class="form-style" style="width: 100px;height: 30px;margin:45px;right:1rem;position: relative;bottom:2rem;padding-right: 0;">
                        <label>Description</label>
                        {{form.Short_Description}}
                    </div>
                    
                    <input type="submit" value="ADD" class="btn btn-primary btn-block" style="background: linear-gradient(90deg, #2D91DE 0%, #754798 100%);
                    color:#FFFFFF;text-transform: uppercase;border-bottom: 2px solid rgba(0, 0, 0, 0.12);position: relative;border:none;
                    height:30;width:20vw;font-size:12px;margin: 30px;top: 75px;letter-spacing: 1px;">
                </form>
            </div>

        </div>
    </section>


    {% endblock content %}
    </html>

info_PJJ/templates/info_PJJ/Learn_From_Home.html
{% extends 'info_PJJ/base.html' %}

{% load static %}

{% block heading %}
<html>

<head>
  <title>Learn From Home</title>
 
</head>
    
{% endblock heading %}

{% block content %}
<body>


<section class="body">
    <h1>Information About Learn From Home</h1>
    
    <h4><a href="{% url 'info_PJJ:Add_News_PJJ' %}" class="btn btn-primary" id="button_add">Add More Information</a></h4>
    
    <div class="row">

      {% for news in News %}
        <div class="col-sm-6">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{{news.Title}}</h5>
              <p class="card-text">{{news.Short_Description}}</p>
              <a href="{{news.Link}}" class="btn btn-primary" id="button">Read More</a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
</section>

</body>
{% endblock content %}

</html>

info_PJJ/templates/info_PJJ/base.html
{% extends 'Home/base.html' %}
{% load static %}


{% block title %}
		{% block heading %}

        {% endblock heading %}
{% endblock title %}


{% block style-css %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock style-css %}


{% block sections %}
	{% block content %}
	
	{% endblock content %}
{% endblock sections %}
    

        
        
    
            