fun/urls.py
from django.urls import path	
from . import views


app_name = 'fun'

urlpatterns = [
    path('', views.fun_home, name='fun_home'),
] 

info_covid/urls.py
from django.urls import path	

from . import views

app_name = 'info_covid'

urlpatterns = [
    path('', views.covid_per_country, name='covid_case_per_country'),
    path('country/', views.country_detail, name='country_detail'),
]

plandemic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('',include('home.urls')),
    path('admin/', admin.site.urls),
    path('Hello', include('hello.urls')),
    path('Information/',include('info_PJJ.urls')),
    path('wfh/', include('informasi_wfh.urls')),
    path('planner/', include('planner.urls')),
    path('accounts/', include('accounts.urls')),
    path('covid/', include('info_covid.urls')),
    path('fun/', include('fun.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

info_covid/models.py
from django.db import models

# Create your models here.
class DataPerCountry(models.Model) :
    name = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    total_cases = models.IntegerField()
    total_cases_per_million = models.FloatField(default=None)
    total_deaths = models.IntegerField()
    total_deaths_per_million = models.FloatField(default=None)
    transmission = models.CharField(max_length=100)

    def __str__(self):
        return self.name



    

   

info_covid/forms.py
from django import forms
from .models import DataPerCountry

class SearchBar(forms.ModelForm):
    class Meta:
        model = DataPerCountry
        fields = [
            'name',
        ]
        widgets = {
            'name' : forms.TextInput(
                attrs={
                'class':'form-style',
                'placeholder':'Search by country name',
                }
            )
        }

info_covid/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages

from .models import DataPerCountry
from info_covid.forms import SearchBar


import csv
import csv23

import os

def covid_per_country(request):
	#import data from csv file to database once
	get_data = DataPerCountry.objects.all().first()
	data_was_created = True if (get_data != None) else False

	if data_was_created==False :
		with csv23.open_reader(os.path.join(os.path.dirname(__file__), 'covid19-per-country-20-11-2020.csv')) as reader:
			for row in reader:
				created = DataPerCountry(
					name = row[0],
					region = row[1],
					total_cases = row[2],
					total_cases_per_million = row[3],
					total_deaths = row[4],
					total_deaths_per_million = row[5],
					transmission = row[6]
					)
				created.save()

	#form
	form = SearchBar(request.GET or None)

	if request.user.is_authenticated:
		database = DataPerCountry.objects.all().reverse()
	else:
		database = DataPerCountry.objects.all().reverse()[:10]

	response = {
		'database_covid': database,
		'form': form
	}
	return render(request, 'covid/info_covid_per_country.html', response)

def country_detail(request):
	query = request.GET.get('name')
	country = DataPerCountry.objects.filter(name=query.title())
	try:
		check = country[0]
		response={
			'country':country
		}
		return render(request, 'covid/country_details.html', response)
	except(IndexError):
		messages.error(request, "Country not found!")
		return redirect('/covid/')
	

info_covid/templates/covid/base-covid.html
{% extends 'Home/base.html' %}
{% load static %}
	{% block title %}
		{% block heading %}

        {% endblock heading %}
	{% endblock title %}

	{% block style-css %}
		<!-- Font Awesome-->
    	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static 'info_covid/covid.css'  %}">
	{% endblock style-css %}
	
	{% block sections %}
		{% block sub-section %}
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
		{% endblock sub-section %}
	{% endblock sections %}
	

info_covid/templates/covid/country_details.html
{% extends 'covid/base-covid.html' %}
{% block heading %}
{% for country in country %}
        <title>{{country.name}}</title>
        {% endfor %}

        {% endblock %}
    
        {% block sub-section %}
        <section class="add-section1">
        {% for country in country %}
            <h1>{{country.name}}</h1>


        <div class="row">

              <div class="card">
                <div class="circle">
                    <div class="card-body">
                        <h5 class="card-title">WHO Region</h5>
                    </div>
                </div>
                <h2>{{country.region}}</h2>
              </div>
            
              <div class="card">
                <div class="circle" id="cases">
                    <div class="card-body">
                        <h5 class="card-title">Total Cases</h5>
                    </div>
                </div>
                <h2  id="blue">{{country.total_cases}}</h2>
              </div>


              <div class="card" >
                    <div class="circle" id="death">
                        <div class="card-body">
                            <h5 class="card-title">Total Death</h5>
                        </div>
                    </div>
                    <h2 id="red">{{country.total_deaths}}</h2>
                </div>

                <div class="card">
                    <div class="circle">
                        <div class="card-body">
                            <h5 class="card-title">Transmission Classification</h5>
                        </div>
                    </div>
                    <h2>{{country.transmission}}</h2>
                </div>
   
     
                <div class="card">
                    <div class="circle">
                        <div class="card-body">
                            <h5 class="card-title">Total Cases per Million</h5>
                        </div>
                    </div>
                    <h2>{{country.total_cases_per_million}}</h2>
                </div>

                <div class="card">
                    <div class="circle">
                        <div class="card-body">
                            <h5 class="card-title">Total Death Per Million</h5>
                        </div>
                    </div>
                    <h2>{{country.total_deaths_per_million}}</h2>
                </div>
          
        </div>
        </section>
        {% endfor %}
        {% endblock %}

info_covid/templates/covid/info_covid_per_country.html
{% extends 'covid/base-covid.html' %}

{% block title %}
<title>COVID Information per Country</title>
{% endblock %}

{% block sub-section %}
<section class="home-section text-center">
  <h3 class="mx-auto mb-4">Coronavirus Disease (COVID-19) Information per Country</h3>

  <!-- messages if country not found -->
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-danger text-left mx-auto {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}

  <form action="{% url 'info_covid:country_detail' %}" method="GET" class="text-left">
    <div class="search-box border rounded">
      {% csrf_token %}
      {{ form.name.errors }}
      {{ form.name }}
      <i class="fas fa-search pr-4"></i>
    </div>
    
  </form>
    <table class="table mx-auto mt-4 text-left table-hover">
      <caption>Data from <a href="https://covid19.who.int/table">WHO Coronavirus Disease (COVID-19) Dashboard</a>. Last updated 20 November 2020</caption>
        <thead>
          <tr>
            <th scope="col" id="th-name">Name</th>
            <th scope="col">WHO Region</th>
            <th scope="col">Total Cases</th>
            <th scope="col">Total Cases per Million</th>
            <th scope="col">Total Death</th>
            <th scope="col">Total Death Per Million</th>
            <th scope="col">Transmission Classification</th>
          </tr>
        </thead>
        <tbody>
          {% for country in database_covid %}
          <tr>
            <td id="th-name">{{country.name}}</td>
            <td>{{country.region}}</td>
            <td>{{country.total_cases}}</td>
            <td>{{country.total_cases_per_million}}</td>
            <td>{{country.total_deaths}}</td>
            <td>{{country.total_deaths_per_million}}</td>
            <td>{{country.transmission}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <p class="more text-center"> Want to see more country? <a class="more ml-1" href="{% url 'login' %}"> Login Now! </a> </p>
</section>
{% endblock %}